name: download

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Cache folder named as "./cache"
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}
      - run: python -m pip install --upgrade pip
      - run: pip install openvino-dev[onnx,pytorch]==2022.3.0
      - run: pip install -r requirements.txt
      - name: Download
        run: python demo.py --prompt "Abstract Wallpaper"
      - name: Save Images
        uses: actions/upload-artifact@v3
        with:
          name: output.png
          path: output.png
